title:              Akeju Paul
tagline:            low level guy
description:        "Just vibing and trying to make code fun again — one project at a time."
url:                http://backendpapa1.github.io

author:
  name:             Akeju Paul
  url:              https://twitter.com/backendpapa
  email:            paulakeju@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
